language: go
go:
  - 1.13.3
env:
  global:
    - SHA512_CMD=sha512sum
    - GO111MODULE=on
matrix:
  include:
  - os: linux
    dist: bionic
  - os: osx
    env: SHA512_CMD=shasum -a 512
  - os: windows
addons:
  sonarcloud:
    organization: 030-github
    token:
      secure: $SONAR_TOKEN
script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - export DELIVERABLE=go-multipart-${TRAVIS_OS_NAME}
  - go build -o $DELIVERABLE
  - $SHA512_CMD $DELIVERABLE > ${DELIVERABLE}.sha512.txt
  - chmod +x $DELIVERABLE
  - if [ $TRAVIS_OS_NAME == linux ]; then ./integration-tests.sh ./${DELIVERABLE}; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TRAVIS_PULL_REQUEST == false ]; then sonar-scanner -Dsonar.projectKey=030_go-multipart -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.exclusions=cmd/**,**/*_test.go -Dsonar.go.coverage.reportPaths=coverage.txt; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TRAVIS_PULL_REQUEST == false ]; then bash <(curl -s https://codecov.io/bash); fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - $DELIVERABLE
    - ${DELIVERABLE}.sha512.txt
  skip_cleanup: true
  on:
    tags: true